//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HomeAssistantDesktop.Resources {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HomeAssistantDesktop.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        public static string Setup_Subtitle {
            get {
                return ResourceManager.GetString("Setup_Subtitle", resourceCulture);
            }
        }

        public static string Setup_UrlPlaceholder {
            get {
                return ResourceManager.GetString("Setup_UrlPlaceholder", resourceCulture);
            }
        }

        public static string Setup_Connect {
            get {
                return ResourceManager.GetString("Setup_Connect", resourceCulture);
            }
        }

        public static string Error_InvalidUrl {
            get {
                return ResourceManager.GetString("Error_InvalidUrl", resourceCulture);
            }
        }

        public static string Error_WebView2InitFailed {
            get {
                return ResourceManager.GetString("Error_WebView2InitFailed", resourceCulture);
            }
        }

        public static string Error_WebView2DownloadLink {
            get {
                return ResourceManager.GetString("Error_WebView2DownloadLink", resourceCulture);
            }
        }

        public static string Error_OfflineTitle {
            get {
                return ResourceManager.GetString("Error_OfflineTitle", resourceCulture);
            }
        }

        public static string Error_Retry {
            get {
                return ResourceManager.GetString("Error_Retry", resourceCulture);
            }
        }

        public static string Error_Settings {
            get {
                return ResourceManager.GetString("Error_Settings", resourceCulture);
            }
        }

        public static string Error_ServerSwitchFailed {
            get {
                return ResourceManager.GetString("Error_ServerSwitchFailed", resourceCulture);
            }
        }

        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }

        public static string Settings_StartupSection {
            get {
                return ResourceManager.GetString("Settings_StartupSection", resourceCulture);
            }
        }

        public static string Settings_StartWithWindows {
            get {
                return ResourceManager.GetString("Settings_StartWithWindows", resourceCulture);
            }
        }

        public static string Settings_WindowSection {
            get {
                return ResourceManager.GetString("Settings_WindowSection", resourceCulture);
            }
        }

        public static string Settings_AlwaysOnTop {
            get {
                return ResourceManager.GetString("Settings_AlwaysOnTop", resourceCulture);
            }
        }

        public static string Settings_ServersSection {
            get {
                return ResourceManager.GetString("Settings_ServersSection", resourceCulture);
            }
        }

        public static string Settings_AddServer {
            get {
                return ResourceManager.GetString("Settings_AddServer", resourceCulture);
            }
        }

        public static string Settings_ServerDetails {
            get {
                return ResourceManager.GetString("Settings_ServerDetails", resourceCulture);
            }
        }

        public static string Settings_Name {
            get {
                return ResourceManager.GetString("Settings_Name", resourceCulture);
            }
        }

        public static string Settings_Url {
            get {
                return ResourceManager.GetString("Settings_Url", resourceCulture);
            }
        }

        public static string Settings_SetAsDefault {
            get {
                return ResourceManager.GetString("Settings_SetAsDefault", resourceCulture);
            }
        }

        public static string Settings_Save {
            get {
                return ResourceManager.GetString("Settings_Save", resourceCulture);
            }
        }

        public static string Settings_Test {
            get {
                return ResourceManager.GetString("Settings_Test", resourceCulture);
            }
        }

        public static string Settings_Cancel {
            get {
                return ResourceManager.GetString("Settings_Cancel", resourceCulture);
            }
        }

        public static string Settings_Edit {
            get {
                return ResourceManager.GetString("Settings_Edit", resourceCulture);
            }
        }

        public static string Settings_Default {
            get {
                return ResourceManager.GetString("Settings_Default", resourceCulture);
            }
        }

        public static string Settings_Delete {
            get {
                return ResourceManager.GetString("Settings_Delete", resourceCulture);
            }
        }

        public static string Settings_AppearanceNote {
            get {
                return ResourceManager.GetString("Settings_AppearanceNote", resourceCulture);
            }
        }

        public static string Settings_ConfirmDelete {
            get {
                return ResourceManager.GetString("Settings_ConfirmDelete", resourceCulture);
            }
        }

        public static string Settings_ConfirmDeleteTitle {
            get {
                return ResourceManager.GetString("Settings_ConfirmDeleteTitle", resourceCulture);
            }
        }

        public static string Test_UrlInvalid {
            get {
                return ResourceManager.GetString("Test_UrlInvalid", resourceCulture);
            }
        }

        public static string Test_UrlInvalidFormat {
            get {
                return ResourceManager.GetString("Test_UrlInvalidFormat", resourceCulture);
            }
        }

        public static string Test_Testing {
            get {
                return ResourceManager.GetString("Test_Testing", resourceCulture);
            }
        }

        public static string Test_Ok {
            get {
                return ResourceManager.GetString("Test_Ok", resourceCulture);
            }
        }

        public static string Test_ReachableWithStatus {
            get {
                return ResourceManager.GetString("Test_ReachableWithStatus", resourceCulture);
            }
        }

        public static string Test_Failed {
            get {
                return ResourceManager.GetString("Test_Failed", resourceCulture);
            }
        }

        public static string Tray_Open {
            get {
                return ResourceManager.GetString("Tray_Open", resourceCulture);
            }
        }

        public static string Tray_CurrentServer {
            get {
                return ResourceManager.GetString("Tray_CurrentServer", resourceCulture);
            }
        }

        public static string Tray_Settings {
            get {
                return ResourceManager.GetString("Tray_Settings", resourceCulture);
            }
        }

        public static string Tray_Exit {
            get {
                return ResourceManager.GetString("Tray_Exit", resourceCulture);
            }
        }

        public static string Tray_NoServers {
            get {
                return ResourceManager.GetString("Tray_NoServers", resourceCulture);
            }
        }

        public static string Status_Connected {
            get {
                return ResourceManager.GetString("Status_Connected", resourceCulture);
            }
        }

        public static string Status_Connecting {
            get {
                return ResourceManager.GetString("Status_Connecting", resourceCulture);
            }
        }

        public static string Status_Offline {
            get {
                return ResourceManager.GetString("Status_Offline", resourceCulture);
            }
        }

        public static string Status_Unknown {
            get {
                return ResourceManager.GetString("Status_Unknown", resourceCulture);
            }
        }

        public static string NewServer_Name {
            get {
                return ResourceManager.GetString("NewServer_Name", resourceCulture);
            }
        }

        public static string NewServer_Url {
            get {
                return ResourceManager.GetString("NewServer_Url", resourceCulture);
            }
        }

        public static string DefaultServer_Name {
            get {
                return ResourceManager.GetString("DefaultServer_Name", resourceCulture);
            }
        }
    }
}
